INFO 2023-11-04 21:40:21,234 autoreload autoreload.py 668 Watching for file changes with StatReloader
INFO 2023-11-04 21:40:21,234 autoreload autoreload.py 668 Watching for file changes with StatReloader
ERROR 2023-11-04 21:40:30,323 user_service user_service.py 64 An exception occured in get_user:
Traceback (most recent call last):
  File "/Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/user_service.py", line 62, in get_user
    return self.user_model.objects.get(id=user_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/models/query.py", line 637, in get
    raise self.model.DoesNotExist(
spotify_analyzer.models.User.DoesNotExist: User matching query does not exist.
ERROR 2023-11-04 21:40:30,323 user_service user_service.py 64 An exception occured in get_user:
Traceback (most recent call last):
  File "/Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/user_service.py", line 62, in get_user
    return self.user_model.objects.get(id=user_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/models/query.py", line 637, in get
    raise self.model.DoesNotExist(
spotify_analyzer.models.User.DoesNotExist: User matching query does not exist.
ERROR 2023-11-04 21:40:30,343 user_service user_service.py 46 An error occurred while creating a user: UNIQUE constraint failed: User.id
Traceback (most recent call last):
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/backends/sqlite3/base.py", line 328, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.IntegrityError: UNIQUE constraint failed: User.id

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/user_service.py", line 40, in create_user
    return self.user_model.objects.create(**user_data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/models/query.py", line 658, in create
    obj.save(force_insert=True, using=self.db)
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/models/base.py", line 814, in save
    self.save_base(
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/models/base.py", line 877, in save_base
    updated = self._save_table(
              ^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/models/base.py", line 1020, in _save_table
    results = self._do_insert(
              ^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/models/base.py", line 1061, in _do_insert
    return manager._insert(
           ^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/models/query.py", line 1805, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/models/sql/compiler.py", line 1822, in execute_sql
    cursor.execute(sql, params)
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/backends/utils.py", line 102, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/backends/utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/backends/sqlite3/base.py", line 328, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.IntegrityError: UNIQUE constraint failed: User.id
ERROR 2023-11-04 21:40:30,343 user_service user_service.py 46 An error occurred while creating a user: UNIQUE constraint failed: User.id
Traceback (most recent call last):
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/backends/sqlite3/base.py", line 328, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.IntegrityError: UNIQUE constraint failed: User.id

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/user_service.py", line 40, in create_user
    return self.user_model.objects.create(**user_data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/models/query.py", line 658, in create
    obj.save(force_insert=True, using=self.db)
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/models/base.py", line 814, in save
    self.save_base(
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/models/base.py", line 877, in save_base
    updated = self._save_table(
              ^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/models/base.py", line 1020, in _save_table
    results = self._do_insert(
              ^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/models/base.py", line 1061, in _do_insert
    return manager._insert(
           ^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/models/query.py", line 1805, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/models/sql/compiler.py", line 1822, in execute_sql
    cursor.execute(sql, params)
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/backends/utils.py", line 102, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/backends/utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/backends/sqlite3/base.py", line 328, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.IntegrityError: UNIQUE constraint failed: User.id
ERROR 2023-11-04 21:40:30,347 user_service user_service.py 64 An exception occured in get_user:
Traceback (most recent call last):
  File "/Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/user_service.py", line 62, in get_user
    return self.user_model.objects.get(id=user_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/models/query.py", line 637, in get
    raise self.model.DoesNotExist(
spotify_analyzer.models.User.DoesNotExist: User matching query does not exist.
ERROR 2023-11-04 21:40:30,347 user_service user_service.py 64 An exception occured in get_user:
Traceback (most recent call last):
  File "/Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/user_service.py", line 62, in get_user
    return self.user_model.objects.get(id=user_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/models/query.py", line 637, in get
    raise self.model.DoesNotExist(
spotify_analyzer.models.User.DoesNotExist: User matching query does not exist.
ERROR 2023-11-04 21:40:30,356 user_service user_service.py 64 An exception occured in get_user:
Traceback (most recent call last):
  File "/Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/user_service.py", line 62, in get_user
    return self.user_model.objects.get(id=user_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/models/query.py", line 637, in get
    raise self.model.DoesNotExist(
spotify_analyzer.models.User.DoesNotExist: User matching query does not exist.
ERROR 2023-11-04 21:40:30,356 user_service user_service.py 64 An exception occured in get_user:
Traceback (most recent call last):
  File "/Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/user_service.py", line 62, in get_user
    return self.user_model.objects.get(id=user_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/models/query.py", line 637, in get
    raise self.model.DoesNotExist(
spotify_analyzer.models.User.DoesNotExist: User matching query does not exist.
INFO 2023-11-04 21:41:23,418 autoreload autoreload.py 266 /Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/user_service.py changed, reloading.
INFO 2023-11-04 21:41:23,418 autoreload autoreload.py 266 /Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/user_service.py changed, reloading.
INFO 2023-11-04 21:41:24,313 autoreload autoreload.py 668 Watching for file changes with StatReloader
INFO 2023-11-04 21:41:24,313 autoreload autoreload.py 668 Watching for file changes with StatReloader
INFO 2023-11-04 21:41:30,715 autoreload autoreload.py 266 /Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/user_service.py changed, reloading.
INFO 2023-11-04 21:41:30,715 autoreload autoreload.py 266 /Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/user_service.py changed, reloading.
INFO 2023-11-04 21:41:31,579 autoreload autoreload.py 668 Watching for file changes with StatReloader
INFO 2023-11-04 21:41:31,579 autoreload autoreload.py 668 Watching for file changes with StatReloader
INFO 2023-11-04 21:42:38,797 user_service user_service.py 64 User does not exist
INFO 2023-11-04 21:42:38,797 user_service user_service.py 64 User does not exist
ERROR 2023-11-04 21:42:38,799 user_service user_service.py 46 An error occurred while creating a user: UNIQUE constraint failed: User.id
Traceback (most recent call last):
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/backends/sqlite3/base.py", line 328, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.IntegrityError: UNIQUE constraint failed: User.id

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/user_service.py", line 40, in create_user
    return self.user_model.objects.create(**user_data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/models/query.py", line 658, in create
    obj.save(force_insert=True, using=self.db)
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/models/base.py", line 814, in save
    self.save_base(
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/models/base.py", line 877, in save_base
    updated = self._save_table(
              ^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/models/base.py", line 1020, in _save_table
    results = self._do_insert(
              ^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/models/base.py", line 1061, in _do_insert
    return manager._insert(
           ^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/models/query.py", line 1805, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/models/sql/compiler.py", line 1822, in execute_sql
    cursor.execute(sql, params)
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/backends/utils.py", line 102, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/backends/utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/backends/sqlite3/base.py", line 328, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.IntegrityError: UNIQUE constraint failed: User.id
ERROR 2023-11-04 21:42:38,799 user_service user_service.py 46 An error occurred while creating a user: UNIQUE constraint failed: User.id
Traceback (most recent call last):
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/backends/sqlite3/base.py", line 328, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.IntegrityError: UNIQUE constraint failed: User.id

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/user_service.py", line 40, in create_user
    return self.user_model.objects.create(**user_data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/models/query.py", line 658, in create
    obj.save(force_insert=True, using=self.db)
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/models/base.py", line 814, in save
    self.save_base(
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/models/base.py", line 877, in save_base
    updated = self._save_table(
              ^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/models/base.py", line 1020, in _save_table
    results = self._do_insert(
              ^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/models/base.py", line 1061, in _do_insert
    return manager._insert(
           ^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/models/query.py", line 1805, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/models/sql/compiler.py", line 1822, in execute_sql
    cursor.execute(sql, params)
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/backends/utils.py", line 102, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/backends/utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/backends/sqlite3/base.py", line 328, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.IntegrityError: UNIQUE constraint failed: User.id
INFO 2023-11-04 21:42:38,806 user_service user_service.py 64 User does not exist
INFO 2023-11-04 21:42:38,806 user_service user_service.py 64 User does not exist
INFO 2023-11-04 21:42:38,807 user_service user_service.py 64 User does not exist
INFO 2023-11-04 21:42:38,807 user_service user_service.py 64 User does not exist
INFO 2023-11-04 21:43:09,806 autoreload autoreload.py 266 /Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/user_service.py changed, reloading.
INFO 2023-11-04 21:43:09,806 autoreload autoreload.py 266 /Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/user_service.py changed, reloading.
INFO 2023-11-04 21:43:10,636 autoreload autoreload.py 668 Watching for file changes with StatReloader
INFO 2023-11-04 21:43:10,636 autoreload autoreload.py 668 Watching for file changes with StatReloader
ERROR 2023-11-04 21:43:13,142 log log.py 241 Internal Server Error: /spotify/auth-code/
ERROR 2023-11-04 21:43:13,142 log log.py 241 Internal Server Error: /spotify/auth-code/
INFO 2023-11-04 21:43:27,986 user_service user_service.py 64 User does not exist
INFO 2023-11-04 21:43:27,986 user_service user_service.py 64 User does not exist
ERROR 2023-11-04 21:43:27,987 user_service user_service.py 46 An error occurred while creating a user: UNIQUE constraint failed: User.id
Traceback (most recent call last):
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/backends/sqlite3/base.py", line 328, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.IntegrityError: UNIQUE constraint failed: User.id

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/user_service.py", line 40, in create_user
    return self.user_model.objects.create(**user_data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/models/query.py", line 658, in create
    obj.save(force_insert=True, using=self.db)
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/models/base.py", line 814, in save
    self.save_base(
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/models/base.py", line 877, in save_base
    updated = self._save_table(
              ^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/models/base.py", line 1020, in _save_table
    results = self._do_insert(
              ^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/models/base.py", line 1061, in _do_insert
    return manager._insert(
           ^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/models/query.py", line 1805, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/models/sql/compiler.py", line 1822, in execute_sql
    cursor.execute(sql, params)
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/backends/utils.py", line 102, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/backends/utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/backends/sqlite3/base.py", line 328, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.IntegrityError: UNIQUE constraint failed: User.id
ERROR 2023-11-04 21:43:27,987 user_service user_service.py 46 An error occurred while creating a user: UNIQUE constraint failed: User.id
Traceback (most recent call last):
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/backends/sqlite3/base.py", line 328, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.IntegrityError: UNIQUE constraint failed: User.id

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/user_service.py", line 40, in create_user
    return self.user_model.objects.create(**user_data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/models/query.py", line 658, in create
    obj.save(force_insert=True, using=self.db)
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/models/base.py", line 814, in save
    self.save_base(
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/models/base.py", line 877, in save_base
    updated = self._save_table(
              ^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/models/base.py", line 1020, in _save_table
    results = self._do_insert(
              ^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/models/base.py", line 1061, in _do_insert
    return manager._insert(
           ^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/models/query.py", line 1805, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/models/sql/compiler.py", line 1822, in execute_sql
    cursor.execute(sql, params)
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/backends/utils.py", line 102, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/backends/utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/backends/sqlite3/base.py", line 328, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.IntegrityError: UNIQUE constraint failed: User.id
INFO 2023-11-04 21:43:27,994 user_service user_service.py 64 User does not exist
INFO 2023-11-04 21:43:27,994 user_service user_service.py 64 User does not exist
INFO 2023-11-04 21:43:27,995 user_service user_service.py 64 User does not exist
INFO 2023-11-04 21:43:27,995 user_service user_service.py 64 User does not exist
INFO 2023-11-04 21:45:37,412 autoreload autoreload.py 668 Watching for file changes with StatReloader
INFO 2023-11-04 21:45:37,412 autoreload autoreload.py 668 Watching for file changes with StatReloader
INFO 2023-11-04 21:45:45,782 user_service user_service.py 64 User does not exist
INFO 2023-11-04 21:45:45,782 user_service user_service.py 64 User does not exist
ERROR 2023-11-04 21:45:45,785 user_service user_service.py 46 An error occurred while creating a user: UNIQUE constraint failed: User.id
Traceback (most recent call last):
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/backends/sqlite3/base.py", line 328, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.IntegrityError: UNIQUE constraint failed: User.id

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/user_service.py", line 40, in create_user
    return self.user_model.objects.create(**user_data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/models/query.py", line 658, in create
    obj.save(force_insert=True, using=self.db)
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/models/base.py", line 814, in save
    self.save_base(
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/models/base.py", line 877, in save_base
    updated = self._save_table(
              ^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/models/base.py", line 1020, in _save_table
    results = self._do_insert(
              ^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/models/base.py", line 1061, in _do_insert
    return manager._insert(
           ^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/models/query.py", line 1805, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/models/sql/compiler.py", line 1822, in execute_sql
    cursor.execute(sql, params)
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/backends/utils.py", line 102, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/backends/utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/backends/sqlite3/base.py", line 328, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.IntegrityError: UNIQUE constraint failed: User.id
ERROR 2023-11-04 21:45:45,785 user_service user_service.py 46 An error occurred while creating a user: UNIQUE constraint failed: User.id
Traceback (most recent call last):
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/backends/sqlite3/base.py", line 328, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.IntegrityError: UNIQUE constraint failed: User.id

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/user_service.py", line 40, in create_user
    return self.user_model.objects.create(**user_data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/models/query.py", line 658, in create
    obj.save(force_insert=True, using=self.db)
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/models/base.py", line 814, in save
    self.save_base(
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/models/base.py", line 877, in save_base
    updated = self._save_table(
              ^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/models/base.py", line 1020, in _save_table
    results = self._do_insert(
              ^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/models/base.py", line 1061, in _do_insert
    return manager._insert(
           ^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/models/query.py", line 1805, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/models/sql/compiler.py", line 1822, in execute_sql
    cursor.execute(sql, params)
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/backends/utils.py", line 102, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/backends/utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/backends/sqlite3/base.py", line 328, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.IntegrityError: UNIQUE constraint failed: User.id
INFO 2023-11-04 21:45:45,791 user_service user_service.py 64 User does not exist
INFO 2023-11-04 21:45:45,791 user_service user_service.py 64 User does not exist
INFO 2023-11-04 21:45:45,792 user_service user_service.py 64 User does not exist
INFO 2023-11-04 21:45:45,792 user_service user_service.py 64 User does not exist
INFO 2023-11-04 21:50:23,623 autoreload autoreload.py 266 /Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/spotify/spotify_service.py changed, reloading.
INFO 2023-11-04 21:50:23,623 autoreload autoreload.py 266 /Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/spotify/spotify_service.py changed, reloading.
INFO 2023-11-04 21:50:24,569 autoreload autoreload.py 668 Watching for file changes with StatReloader
INFO 2023-11-04 21:50:24,569 autoreload autoreload.py 668 Watching for file changes with StatReloader
INFO 2023-11-04 21:52:51,823 autoreload autoreload.py 266 /Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/spotify/spotify_service.py changed, reloading.
INFO 2023-11-04 21:52:51,823 autoreload autoreload.py 266 /Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/spotify/spotify_service.py changed, reloading.
INFO 2023-11-04 21:52:52,324 autoreload autoreload.py 668 Watching for file changes with StatReloader
INFO 2023-11-04 21:52:52,324 autoreload autoreload.py 668 Watching for file changes with StatReloader
INFO 2023-11-04 21:52:53,508 autoreload autoreload.py 266 /Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/spotify/spotify_service.py changed, reloading.
INFO 2023-11-04 21:52:53,508 autoreload autoreload.py 266 /Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/spotify/spotify_service.py changed, reloading.
INFO 2023-11-04 21:52:53,932 autoreload autoreload.py 668 Watching for file changes with StatReloader
INFO 2023-11-04 21:52:53,932 autoreload autoreload.py 668 Watching for file changes with StatReloader
INFO 2023-11-04 21:53:01,182 autoreload autoreload.py 266 /Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/spotify/spotify_service.py changed, reloading.
INFO 2023-11-04 21:53:01,182 autoreload autoreload.py 266 /Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/spotify/spotify_service.py changed, reloading.
INFO 2023-11-04 21:53:01,999 autoreload autoreload.py 668 Watching for file changes with StatReloader
INFO 2023-11-04 21:53:01,999 autoreload autoreload.py 668 Watching for file changes with StatReloader
INFO 2023-11-04 22:03:59,632 autoreload autoreload.py 266 /Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/spotify/spotify_service.py changed, reloading.
INFO 2023-11-04 22:03:59,632 autoreload autoreload.py 266 /Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/spotify/spotify_service.py changed, reloading.
INFO 2023-11-04 22:04:00,687 autoreload autoreload.py 668 Watching for file changes with StatReloader
INFO 2023-11-04 22:04:00,687 autoreload autoreload.py 668 Watching for file changes with StatReloader
INFO 2023-11-04 22:04:06,073 autoreload autoreload.py 266 /Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/spotify/spotify_service.py changed, reloading.
INFO 2023-11-04 22:04:06,073 autoreload autoreload.py 266 /Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/spotify/spotify_service.py changed, reloading.
INFO 2023-11-04 22:04:06,918 autoreload autoreload.py 668 Watching for file changes with StatReloader
INFO 2023-11-04 22:04:06,918 autoreload autoreload.py 668 Watching for file changes with StatReloader
INFO 2023-11-04 22:04:09,255 autoreload autoreload.py 266 /Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/spotify/spotify_service.py changed, reloading.
INFO 2023-11-04 22:04:09,255 autoreload autoreload.py 266 /Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/spotify/spotify_service.py changed, reloading.
INFO 2023-11-04 22:04:10,102 autoreload autoreload.py 668 Watching for file changes with StatReloader
INFO 2023-11-04 22:04:10,102 autoreload autoreload.py 668 Watching for file changes with StatReloader
INFO 2023-11-04 22:05:23,480 autoreload autoreload.py 266 /Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/spotify/spotify_service.py changed, reloading.
INFO 2023-11-04 22:05:23,480 autoreload autoreload.py 266 /Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/spotify/spotify_service.py changed, reloading.
INFO 2023-11-04 22:05:23,972 autoreload autoreload.py 668 Watching for file changes with StatReloader
INFO 2023-11-04 22:05:23,972 autoreload autoreload.py 668 Watching for file changes with StatReloader
INFO 2023-11-04 22:05:29,199 autoreload autoreload.py 266 /Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/spotify/spotify_service.py changed, reloading.
INFO 2023-11-04 22:05:29,199 autoreload autoreload.py 266 /Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/spotify/spotify_service.py changed, reloading.
INFO 2023-11-04 22:05:29,974 autoreload autoreload.py 668 Watching for file changes with StatReloader
INFO 2023-11-04 22:05:29,974 autoreload autoreload.py 668 Watching for file changes with StatReloader
INFO 2023-11-04 22:05:35,374 autoreload autoreload.py 266 /Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/spotify/spotify_service.py changed, reloading.
INFO 2023-11-04 22:05:35,374 autoreload autoreload.py 266 /Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/spotify/spotify_service.py changed, reloading.
INFO 2023-11-04 22:05:36,263 autoreload autoreload.py 668 Watching for file changes with StatReloader
INFO 2023-11-04 22:05:36,263 autoreload autoreload.py 668 Watching for file changes with StatReloader
INFO 2023-11-04 22:06:52,698 autoreload autoreload.py 266 /Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/spotify/spotify_service.py changed, reloading.
INFO 2023-11-04 22:06:52,698 autoreload autoreload.py 266 /Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/spotify/spotify_service.py changed, reloading.
INFO 2023-11-04 22:06:53,573 autoreload autoreload.py 668 Watching for file changes with StatReloader
INFO 2023-11-04 22:06:53,573 autoreload autoreload.py 668 Watching for file changes with StatReloader
INFO 2023-11-04 22:06:54,891 autoreload autoreload.py 266 /Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/spotify/spotify_service.py changed, reloading.
INFO 2023-11-04 22:06:54,891 autoreload autoreload.py 266 /Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/spotify/spotify_service.py changed, reloading.
INFO 2023-11-04 22:06:55,780 autoreload autoreload.py 668 Watching for file changes with StatReloader
INFO 2023-11-04 22:06:55,780 autoreload autoreload.py 668 Watching for file changes with StatReloader
INFO 2023-11-04 22:06:59,127 autoreload autoreload.py 266 /Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/spotify/spotify_service.py changed, reloading.
INFO 2023-11-04 22:06:59,127 autoreload autoreload.py 266 /Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/spotify/spotify_service.py changed, reloading.
INFO 2023-11-04 22:07:00,029 autoreload autoreload.py 668 Watching for file changes with StatReloader
INFO 2023-11-04 22:07:00,029 autoreload autoreload.py 668 Watching for file changes with StatReloader
INFO 2023-11-04 22:07:04,401 autoreload autoreload.py 266 /Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/spotify/spotify_service.py changed, reloading.
INFO 2023-11-04 22:07:04,401 autoreload autoreload.py 266 /Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/spotify/spotify_service.py changed, reloading.
INFO 2023-11-04 22:07:05,296 autoreload autoreload.py 668 Watching for file changes with StatReloader
INFO 2023-11-04 22:07:05,296 autoreload autoreload.py 668 Watching for file changes with StatReloader
INFO 2023-11-04 22:11:00,750 autoreload autoreload.py 266 /Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/spotify/spotify_service.py changed, reloading.
INFO 2023-11-04 22:11:00,750 autoreload autoreload.py 266 /Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/spotify/spotify_service.py changed, reloading.
INFO 2023-11-04 22:11:01,660 autoreload autoreload.py 668 Watching for file changes with StatReloader
INFO 2023-11-04 22:11:01,660 autoreload autoreload.py 668 Watching for file changes with StatReloader
INFO 2023-11-04 22:11:07,043 autoreload autoreload.py 266 /Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/spotify/spotify_service.py changed, reloading.
INFO 2023-11-04 22:11:07,043 autoreload autoreload.py 266 /Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/spotify/spotify_service.py changed, reloading.
INFO 2023-11-04 22:11:07,868 autoreload autoreload.py 668 Watching for file changes with StatReloader
INFO 2023-11-04 22:11:07,868 autoreload autoreload.py 668 Watching for file changes with StatReloader
INFO 2023-11-04 22:11:13,260 autoreload autoreload.py 266 /Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/spotify/spotify_service.py changed, reloading.
INFO 2023-11-04 22:11:13,260 autoreload autoreload.py 266 /Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/spotify/spotify_service.py changed, reloading.
INFO 2023-11-04 22:11:14,133 autoreload autoreload.py 668 Watching for file changes with StatReloader
INFO 2023-11-04 22:11:14,133 autoreload autoreload.py 668 Watching for file changes with StatReloader
INFO 2023-11-04 22:11:18,506 autoreload autoreload.py 266 /Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/spotify/spotify_service.py changed, reloading.
INFO 2023-11-04 22:11:18,506 autoreload autoreload.py 266 /Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/spotify/spotify_service.py changed, reloading.
INFO 2023-11-04 22:11:19,457 autoreload autoreload.py 668 Watching for file changes with StatReloader
INFO 2023-11-04 22:11:19,457 autoreload autoreload.py 668 Watching for file changes with StatReloader
INFO 2023-11-04 22:12:42,059 autoreload autoreload.py 266 /Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/spotify/spotify_service.py changed, reloading.
INFO 2023-11-04 22:12:42,059 autoreload autoreload.py 266 /Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/spotify/spotify_service.py changed, reloading.
INFO 2023-11-04 22:12:42,528 autoreload autoreload.py 668 Watching for file changes with StatReloader
INFO 2023-11-04 22:12:42,528 autoreload autoreload.py 668 Watching for file changes with StatReloader
INFO 2023-11-04 22:12:46,738 autoreload autoreload.py 266 /Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/spotify/spotify_service.py changed, reloading.
INFO 2023-11-04 22:12:46,738 autoreload autoreload.py 266 /Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/spotify/spotify_service.py changed, reloading.
INFO 2023-11-04 22:12:47,183 autoreload autoreload.py 668 Watching for file changes with StatReloader
INFO 2023-11-04 22:12:47,183 autoreload autoreload.py 668 Watching for file changes with StatReloader
INFO 2023-11-04 22:12:57,479 autoreload autoreload.py 266 /Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/spotify/spotify_service.py changed, reloading.
INFO 2023-11-04 22:12:57,479 autoreload autoreload.py 266 /Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/spotify/spotify_service.py changed, reloading.
INFO 2023-11-04 22:12:58,459 autoreload autoreload.py 668 Watching for file changes with StatReloader
INFO 2023-11-04 22:12:58,459 autoreload autoreload.py 668 Watching for file changes with StatReloader
INFO 2023-11-04 22:13:01,830 autoreload autoreload.py 266 /Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/spotify/spotify_service.py changed, reloading.
INFO 2023-11-04 22:13:01,830 autoreload autoreload.py 266 /Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/spotify/spotify_service.py changed, reloading.
INFO 2023-11-04 22:13:02,707 autoreload autoreload.py 668 Watching for file changes with StatReloader
INFO 2023-11-04 22:13:02,707 autoreload autoreload.py 668 Watching for file changes with StatReloader
INFO 2023-11-04 22:14:26,296 autoreload autoreload.py 266 /Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/spotify/spotify_service.py changed, reloading.
INFO 2023-11-04 22:14:26,296 autoreload autoreload.py 266 /Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/spotify/spotify_service.py changed, reloading.
INFO 2023-11-04 22:14:26,798 autoreload autoreload.py 668 Watching for file changes with StatReloader
INFO 2023-11-04 22:14:26,798 autoreload autoreload.py 668 Watching for file changes with StatReloader
INFO 2023-11-04 22:15:39,968 autoreload autoreload.py 266 /Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/spotify/spotify_service.py changed, reloading.
INFO 2023-11-04 22:15:39,968 autoreload autoreload.py 266 /Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/spotify/spotify_service.py changed, reloading.
INFO 2023-11-04 22:15:40,807 autoreload autoreload.py 668 Watching for file changes with StatReloader
INFO 2023-11-04 22:15:40,807 autoreload autoreload.py 668 Watching for file changes with StatReloader
INFO 2023-11-04 22:15:42,108 autoreload autoreload.py 266 /Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/spotify/spotify_service.py changed, reloading.
INFO 2023-11-04 22:15:42,108 autoreload autoreload.py 266 /Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/spotify/spotify_service.py changed, reloading.
INFO 2023-11-04 22:15:42,954 autoreload autoreload.py 668 Watching for file changes with StatReloader
INFO 2023-11-04 22:15:42,954 autoreload autoreload.py 668 Watching for file changes with StatReloader
INFO 2023-11-04 22:15:58,656 autoreload autoreload.py 266 /Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/spotify/spotify_service.py changed, reloading.
INFO 2023-11-04 22:15:58,656 autoreload autoreload.py 266 /Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/spotify/spotify_service.py changed, reloading.
INFO 2023-11-04 22:15:59,514 autoreload autoreload.py 668 Watching for file changes with StatReloader
INFO 2023-11-04 22:15:59,514 autoreload autoreload.py 668 Watching for file changes with StatReloader
INFO 2023-11-04 22:16:02,849 autoreload autoreload.py 266 /Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/spotify/spotify_service.py changed, reloading.
INFO 2023-11-04 22:16:02,849 autoreload autoreload.py 266 /Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/spotify/spotify_service.py changed, reloading.
INFO 2023-11-04 22:16:03,704 autoreload autoreload.py 668 Watching for file changes with StatReloader
INFO 2023-11-04 22:16:03,704 autoreload autoreload.py 668 Watching for file changes with StatReloader
INFO 2023-11-04 22:16:12,182 autoreload autoreload.py 266 /Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/spotify/spotify_service.py changed, reloading.
INFO 2023-11-04 22:16:12,182 autoreload autoreload.py 266 /Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/spotify/spotify_service.py changed, reloading.
INFO 2023-11-04 22:16:13,097 autoreload autoreload.py 668 Watching for file changes with StatReloader
INFO 2023-11-04 22:16:13,097 autoreload autoreload.py 668 Watching for file changes with StatReloader
INFO 2023-11-04 22:17:09,937 autoreload autoreload.py 266 /Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/spotify/spotify_service.py changed, reloading.
INFO 2023-11-04 22:17:09,937 autoreload autoreload.py 266 /Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/spotify/spotify_service.py changed, reloading.
INFO 2023-11-04 22:17:10,829 autoreload autoreload.py 668 Watching for file changes with StatReloader
INFO 2023-11-04 22:17:10,829 autoreload autoreload.py 668 Watching for file changes with StatReloader
INFO 2023-11-04 22:17:13,144 autoreload autoreload.py 266 /Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/spotify/spotify_service.py changed, reloading.
INFO 2023-11-04 22:17:13,144 autoreload autoreload.py 266 /Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/spotify/spotify_service.py changed, reloading.
INFO 2023-11-04 22:17:14,065 autoreload autoreload.py 668 Watching for file changes with StatReloader
INFO 2023-11-04 22:17:14,065 autoreload autoreload.py 668 Watching for file changes with StatReloader
INFO 2023-11-04 22:17:18,419 autoreload autoreload.py 266 /Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/spotify/spotify_service.py changed, reloading.
INFO 2023-11-04 22:17:18,419 autoreload autoreload.py 266 /Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/spotify/spotify_service.py changed, reloading.
INFO 2023-11-04 22:17:19,243 autoreload autoreload.py 668 Watching for file changes with StatReloader
INFO 2023-11-04 22:17:19,243 autoreload autoreload.py 668 Watching for file changes with StatReloader
INFO 2023-11-04 22:17:21,574 autoreload autoreload.py 266 /Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/spotify/spotify_service.py changed, reloading.
INFO 2023-11-04 22:17:21,574 autoreload autoreload.py 266 /Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/spotify/spotify_service.py changed, reloading.
INFO 2023-11-04 22:17:22,433 autoreload autoreload.py 668 Watching for file changes with StatReloader
INFO 2023-11-04 22:17:22,433 autoreload autoreload.py 668 Watching for file changes with StatReloader
INFO 2023-11-04 22:17:24,751 autoreload autoreload.py 266 /Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/spotify/spotify_service.py changed, reloading.
INFO 2023-11-04 22:17:24,751 autoreload autoreload.py 266 /Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/spotify/spotify_service.py changed, reloading.
INFO 2023-11-04 22:17:25,609 autoreload autoreload.py 668 Watching for file changes with StatReloader
INFO 2023-11-04 22:17:25,609 autoreload autoreload.py 668 Watching for file changes with StatReloader
INFO 2023-11-04 22:17:26,905 autoreload autoreload.py 266 /Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/spotify/spotify_service.py changed, reloading.
INFO 2023-11-04 22:17:26,905 autoreload autoreload.py 266 /Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/spotify/spotify_service.py changed, reloading.
INFO 2023-11-04 22:17:27,787 autoreload autoreload.py 668 Watching for file changes with StatReloader
INFO 2023-11-04 22:17:27,787 autoreload autoreload.py 668 Watching for file changes with StatReloader
INFO 2023-11-04 22:17:34,234 autoreload autoreload.py 266 /Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/spotify/spotify_service.py changed, reloading.
INFO 2023-11-04 22:17:34,234 autoreload autoreload.py 266 /Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/spotify/spotify_service.py changed, reloading.
INFO 2023-11-04 22:17:35,106 autoreload autoreload.py 668 Watching for file changes with StatReloader
INFO 2023-11-04 22:17:35,106 autoreload autoreload.py 668 Watching for file changes with StatReloader
INFO 2023-11-04 22:19:14,966 autoreload autoreload.py 266 /Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/spotify/spotify_service.py changed, reloading.
INFO 2023-11-04 22:19:14,966 autoreload autoreload.py 266 /Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/spotify/spotify_service.py changed, reloading.
INFO 2023-11-04 22:19:15,580 autoreload autoreload.py 668 Watching for file changes with StatReloader
INFO 2023-11-04 22:19:15,580 autoreload autoreload.py 668 Watching for file changes with StatReloader
INFO 2023-11-04 22:30:05,725 autoreload autoreload.py 266 /Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/spotify/spotify_service.py changed, reloading.
INFO 2023-11-04 22:30:05,725 autoreload autoreload.py 266 /Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/spotify/spotify_service.py changed, reloading.
INFO 2023-11-04 22:30:06,368 autoreload autoreload.py 668 Watching for file changes with StatReloader
INFO 2023-11-04 22:30:06,368 autoreload autoreload.py 668 Watching for file changes with StatReloader
